language: "en"
intents:
  TimerStop:
    data:
      - sentences:
          - "[(could|would) you] (stop|cancel|turn off) [the] {entity_id} timer[s]"
      - sentences:
          - "[(could|would) you] (stop|cancel|turn off) [the] timer"
        slots:
          entity_id: "null"
lists:
  entity_id:
    values:
      - in: "first"
        out: "timer.timer1"
      - in: "second"
        out: "timer.timer2"
      - in: "third"
        out: "timer.timer3"
      - in: "(all|every)"
        out: "all"
        
responses:
  intents:
    TimerStop:
      default: >
        {% set timer_amount = states.timer|selectattr('state','eq','active')|list|length %}
        {% if timer_amount == 0 %}
        There are no timers active at this moment.
        {% elif (timer_amount == 1 and slots.entity_id == 'null') or states('timer.' + slots.entity_id) == 'active'%}
        {{ (["Understood. ", "Sure. ", "Of course. ", ""] | random) }}{{ (["Cancelled.", "Timer cancelled.", "Stopped timer.", "Timer stopped.", "Deactivated.", "Timer deactivated.", "Timer turned off.", "Turned off timer."] | random) }}
        {% elif slots.entity_id == 'all' %}
        {{ (["Understood. ", "Sure. ", "Of course. ", ""] | random) }}{{ (["All timers cancelled.", "Timers cancelled.", "Stopped all timers.", "All timers deactivated.", "Deactivated all timers.", "Timers turned off.", "Turned off all timers."] | random) }}
        {% else %}
          {% if states('timer.' + slots.entity_id) != 'active' and slots.entity_id != 'null' %}
          This timer is currently inactive. {% 
          else%}{% if timer_amount == 1 %}Currently there is only 1 timer active. {% 
          else %}Currently there are {{ timer_amount }} timers active. {% endif 
          %}{{ (["Please specificy which timer you wish to cancel.", "Please specificy which timer you want to deactivate.", "Please name which timer you want to stop.", ""] | random) }}{%
          endif %}{% endif %}
