language: "nl"
intents:
  TimerStop:
    data:
      - sentences:
          - "(stop|annuleer|<zou>) [de] {entity_id} timer[s] [[willen|kunnen] <doe>] [stoppen|annuleren|uitzetten]"
          - "(stop|annuleer|<zou>) timer {entity_id} [[willen|kunnen] <doe>] [stoppen|annuleren|uitzetten]"
      - sentences:
          - "(stop|annuleer|<zou>) [de] timer [[willen|kunnen] <doe>] [stoppen|annuleren|uitzetten]"
        slots:
          entity_id: "null"
lists:
  entity_id:
    values:
      - in: "eerste"
        out: "timer.timer1"
      - in: "tweede"
        out: "timer.timer2"
      - in: "derde"
        out: "timer.timer3"
      - in: "(alle|iedere)"
        out: "all"
        
responses:
  intents:
    TimerStop:
      default: >
        {% set timer_amount = states.timer|selectattr('state','eq','active')|list|length %}
        {% if timer_amount == 0 %}
        Er zijn momenteel geen timers actief.
        {% elif (timer_amount == 1 and slots.entity_id == 'null') or states(slots.entity_id) == 'active'%}
        {{ (["Akkoord. ", "Begrepen. ", "Goed. ", ""] | random) }}{{ (["Geannuleerd.", "Timer geannuleerd.", "Gestopt.", "Timer gestopt.", "Gedeactiveerd.", "Timer gedeactiveerd.", "Timer uitgeschakeld.", "Uitgeschakeld."] | random) }}
        {% elif slots.entity_id == 'all' %}
        {{ (["Akkoord. ", "Begrepen. ", "Goed. ", ""] | random) }}{{ (["Alle timers geannuleerd.", "Timers geannuleerd.", "Alle timers gestopt.", "Timers gestopt.", "Alle timers gedeactiveerd.", "Timers gedeactiveerd.", "Timers uitgeschakeld.", "Alle timers uitgeschakeld."] | random) }}
        {% else %}
          {% if states(slots.entity_id) != 'active' and slots.entity_id != 'null' %}
          Deze timer is momenteel niet actief. {% 
          else%}{% if timer_amount == 1 %}Er is momenteel 1 timer actief. {% 
          else %}Er zijn momenteel {{ timer_amount }} timers actief. {% endif 
          %}{{ (["Specificeer alstublieft welke timer u wilt stoppen.", "Geef alstublieft aan welke timer u wilt stoppen.", "Benoem alstublieft welke timer u wilt stoppen.", ""] | random) }}{%
          endif %}{% endif %}
