language: "nl"
intents:
  TimerDuration:
    data:
      - sentences:
          - "(hoe lang|hoeveel tijd) nog op de {entity_id} timer"
          - "hoe lang duurt de {entity_id} timer nog"
      - sentences:
          - "(hoe lang|hoeveel tijd) nog op de timer[s]"
          - "hoe lang [duurt|duren] de timer[s] nog"
        slots:
          entity_id: "null"
lists:
  entity_id:
    values:
      - in: "eerste"
        out: "timer.timer1"
      - in: "tweede"
        out: "timer.timer2"
      - in: "derde"
        out: "timer.timer3"
      - in: "(alle|iedere)"
        out: "timer.timer1, timer.timer2, timer.timer3"
        
responses:
  intents:
    TimerDuration:
      default: >
        {% set timer_amount = states.timer|selectattr('state','eq','active')|list|length %}
        {% if timer_amount == 0 %}
        Er zijn momenteel geen timers actief. 
        {% else %}
          {% set active_timers = states.timer|selectattr('state', 'eq', 'active')|list %}{%
             if active_timers|length == 0 %}Er zijn momenteel geen timers actief. {%
             elif active_timers|length > 1 %}Er zijn momenteel {{active_timers|length }} timers actief. {%
             endif %}{%
             for timer in active_timers %}{%
             set timer_id = timer.entity_id %}{%
             set timer_finishes_at = state_attr(timer_id, 'finishes_at') %}{%
  
             set time_remaining = as_datetime(timer_finishes_at) - now() %}{%
             set hours_remaining = time_remaining.total_seconds() // 3600 %}{%
             set minutes_remaining = (time_remaining.total_seconds() % 3600) // 60 %}{%
             set seconds_remaining = time_remaining.total_seconds() % 60 %}{%
             
             if timer.state == "active" or timer.state == "paused" %}{%
               if slots.entity_id != timer_id 
                 %}Timer {{ timer_id[11:] }} {%
                 if timer.state == "paused" %} is gepauzeerd en {% endif %}heeft nog {%
               else %}Nog {% endif %}{%
               if hours_remaining > 0 %}{{ hours_remaining | round }} uur {% endif %}{%
               if minutes_remaining == 1 %}1 minuut {% endif %}{%
               if minutes_remaining > 1 %}{{ minutes_remaining | round }} minuten {% endif %}{%
               if seconds_remaining == 1 and hours_remaining == 0%}1 seconde {% endif %}{%
               if seconds_remaining > 1 and hours_remaining == 0 %}{{ seconds_remaining | round }} seconden {% endif %}te gaan. {%
             endif %}{%
             endfor %}
        {% endif %}
